type User   {
  userName: String! 
  walletAddress: String!
  games: [Game!] @relation
}

type Game {
  gameName: String!
  walletAmount: Int
  networkName: String!
  networkDescription: String!
  start: Date
  end: Date
  user: User @relation
  shows: [Show!] @relation
}

type Show  {  
  showName: String!
  rating: Int!
  showDescription: String!
  game: Game! @relation
}



type Query {
  allUsers: [User]
  userByUserName(userName: String!): User
}

type Mutation {
  addShowsToGame()
}
