type User {
  id: ID
  username: String!
  walletAddress: String!
  games: [Game!] @relation

}


type Game {
  user: User!
  network: String!
  amount: Int!
  start: Date!
  end: Date!
  shows: [Show!] @relation
}

type Show {
  game : Game!
  name: String!
  rating: Int!
  description: String!
}

type CurrentNetworks {
  NetworkNames: [String!]
}