type User   {
  username: ID!
  walletAddress: String!
  networks: [Network!] @relation
  amount: Int
  start: Date
  end: Date
 
}

type Show  {  
  name: String!
  rating: Int!
  description: String!
  network: Network!
}

type Network {
  name: String!
  rating: Int!
  description: String!
  user: User!
  shows: [Show!] @relation
}


type Query {
  # allGames: [Game]
  allUsers: [User]
  allNetworks: [Network]
  allShows: [Show]
  userByUserName(username: ID!): User
 
}