-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias UpdateUserRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.UserInput
    }


{-| Update an existing document in the collection of 'User'

  - id - The 'User' document's ID
  - data - 'User' input values

-}
updateUser : UpdateUserRequiredArguments -> SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) RootMutation
updateUser requiredArgs object_ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs.data Api.InputObject.encodeUserInput ] object_ (identity >> Decode.nullable)


type alias DeleteShowRequiredArguments =
    { id : Api.ScalarCodecs.Id }


{-| Delete an existing document in the collection of 'Show'

  - id - The 'Show' document's ID

-}
deleteShow : DeleteShowRequiredArguments -> SelectionSet decodesTo Api.Object.Show -> SelectionSet (Maybe decodesTo) RootMutation
deleteShow requiredArgs object_ =
    Object.selectionForCompositeField "deleteShow" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)


type alias CreateUserRequiredArguments =
    { data : Api.InputObject.UserInput }


{-| Create a new document in the collection of 'User'

  - data - 'User' input values

-}
createUser : CreateUserRequiredArguments -> SelectionSet decodesTo Api.Object.User -> SelectionSet decodesTo RootMutation
createUser requiredArgs object_ =
    Object.selectionForCompositeField "createUser" [ Argument.required "data" requiredArgs.data Api.InputObject.encodeUserInput ] object_ identity


type alias DeleteNetworkRequiredArguments =
    { id : Api.ScalarCodecs.Id }


{-| Delete an existing document in the collection of 'Network'

  - id - The 'Network' document's ID

-}
deleteNetwork : DeleteNetworkRequiredArguments -> SelectionSet decodesTo Api.Object.Network -> SelectionSet (Maybe decodesTo) RootMutation
deleteNetwork requiredArgs object_ =
    Object.selectionForCompositeField "deleteNetwork" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)


type alias CreateShowRequiredArguments =
    { data : Api.InputObject.ShowInput }


{-| Create a new document in the collection of 'Show'

  - data - 'Show' input values

-}
createShow : CreateShowRequiredArguments -> SelectionSet decodesTo Api.Object.Show -> SelectionSet decodesTo RootMutation
createShow requiredArgs object_ =
    Object.selectionForCompositeField "createShow" [ Argument.required "data" requiredArgs.data Api.InputObject.encodeShowInput ] object_ identity


type alias DeleteUserRequiredArguments =
    { id : Api.ScalarCodecs.Id }


{-| Delete an existing document in the collection of 'User'

  - id - The 'User' document's ID

-}
deleteUser : DeleteUserRequiredArguments -> SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) RootMutation
deleteUser requiredArgs object_ =
    Object.selectionForCompositeField "deleteUser" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)


type alias UpdateShowRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.ShowInput
    }


{-| Update an existing document in the collection of 'Show'

  - id - The 'Show' document's ID
  - data - 'Show' input values

-}
updateShow : UpdateShowRequiredArguments -> SelectionSet decodesTo Api.Object.Show -> SelectionSet (Maybe decodesTo) RootMutation
updateShow requiredArgs object_ =
    Object.selectionForCompositeField "updateShow" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs.data Api.InputObject.encodeShowInput ] object_ (identity >> Decode.nullable)


type alias UpdateNetworkRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.NetworkInput
    }


{-| Update an existing document in the collection of 'Network'

  - id - The 'Network' document's ID
  - data - 'Network' input values

-}
updateNetwork : UpdateNetworkRequiredArguments -> SelectionSet decodesTo Api.Object.Network -> SelectionSet (Maybe decodesTo) RootMutation
updateNetwork requiredArgs object_ =
    Object.selectionForCompositeField "updateNetwork" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs.data Api.InputObject.encodeNetworkInput ] object_ (identity >> Decode.nullable)


type alias CreateNetworkRequiredArguments =
    { data : Api.InputObject.NetworkInput }


{-| Create a new document in the collection of 'Network'

  - data - 'Network' input values

-}
createNetwork : CreateNetworkRequiredArguments -> SelectionSet decodesTo Api.Object.Network -> SelectionSet decodesTo RootMutation
createNetwork requiredArgs object_ =
    Object.selectionForCompositeField "createNetwork" [ Argument.required "data" requiredArgs.data Api.InputObject.encodeNetworkInput ] object_ identity
