-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type AvailableNetwork
    = AvailableNetwork


type AvailableNetworkPage
    = AvailableNetworkPage


type AvalableShow
    = AvalableShow


type AvalableShowPage
    = AvalableShowPage


type CurrentNetworks
    = CurrentNetworks


type Game
    = Game


type GamePage
    = GamePage


type Show
    = Show


type User
    = User
