-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Network
    = Network


type NetworkPage
    = NetworkPage


type Show
    = Show


type ShowPage
    = ShowPage


type User
    = User


type UserPage
    = UserPage
