-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type AvailableNetwork
    = AvailableNetwork


type AvailableNetworkPage
    = AvailableNetworkPage


type Show
    = Show


type User
    = User


type UserPage
    = UserPage
