-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Game exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


networkDescription : SelectionSet String Api.Object.Game
networkDescription =
    Object.selectionForField "String" "networkDescription" [] Decode.string


gameName : SelectionSet String Api.Object.Game
gameName =
    Object.selectionForField "String" "gameName" [] Decode.string


{-| The document's ID.
-}
id_ : SelectionSet Api.ScalarCodecs.Id Api.Object.Game
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


walletAmount : SelectionSet (Maybe Int) Api.Object.Game
walletAmount =
    Object.selectionForField "(Maybe Int)" "walletAmount" [] (Decode.int |> Decode.nullable)


end : SelectionSet (Maybe Api.ScalarCodecs.Date) Api.Object.Game
end =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "end" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


networkName : SelectionSet String Api.Object.Game
networkName =
    Object.selectionForField "String" "networkName" [] Decode.string


shows : SelectionSet decodesTo Api.Object.Show -> SelectionSet (Maybe (List decodesTo)) Api.Object.Game
shows object_ =
    Object.selectionForCompositeField "shows" [] object_ (identity >> Decode.list >> Decode.nullable)


start : SelectionSet (Maybe Api.ScalarCodecs.Date) Api.Object.Game
start =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "start" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


user : SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) Api.Object.Game
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)


{-| The document's timestamp.
-}
ts_ : SelectionSet Api.ScalarCodecs.Long Api.Object.Game
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecLong |> .decoder)
