-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Show exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


showDescription : SelectionSet String Api.Object.Show
showDescription =
    Object.selectionForField "String" "showDescription" [] Decode.string


{-| The document's ID.
-}
id_ : SelectionSet ScalarCodecs.Id Api.Object.Show
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


showName : SelectionSet String Api.Object.Show
showName =
    Object.selectionForField "String" "showName" [] Decode.string


rating : SelectionSet Int Api.Object.Show
rating =
    Object.selectionForField "Int" "rating" [] Decode.int


game : SelectionSet decodesTo Api.Object.Game -> SelectionSet decodesTo Api.Object.Show
game object_ =
    Object.selectionForCompositeField "game" [] object_ identity


{-| The document's timestamp.
-}
ts_ : SelectionSet ScalarCodecs.Long Api.Object.Show
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecLong |> .decoder)
