-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


network : SelectionSet (Maybe String) Api.Object.User
network =
    Object.selectionForField "(Maybe String)" "network" [] (Decode.string |> Decode.nullable)


username : SelectionSet Api.ScalarCodecs.Id Api.Object.User
username =
    Object.selectionForField "ScalarCodecs.Id" "username" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The document's ID.
-}
id_ : SelectionSet Api.ScalarCodecs.Id Api.Object.User
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


walletAddress : SelectionSet String Api.Object.User
walletAddress =
    Object.selectionForField "String" "walletAddress" [] Decode.string


amount : SelectionSet (Maybe Int) Api.Object.User
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


end : SelectionSet (Maybe Api.ScalarCodecs.Date) Api.Object.User
end =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "end" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


shows : SelectionSet decodesTo Api.Object.Show -> SelectionSet (Maybe (List decodesTo)) Api.Object.User
shows object_ =
    Object.selectionForCompositeField "shows" [] object_ (identity >> Decode.list >> Decode.nullable)


start : SelectionSet (Maybe Api.ScalarCodecs.Date) Api.Object.User
start =
    Object.selectionForField "(Maybe ScalarCodecs.Date)" "start" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder |> Decode.nullable)


{-| The document's timestamp.
-}
ts_ : SelectionSet Api.ScalarCodecs.Long Api.Object.User
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecLong |> .decoder)
